// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo6zyjs1xJv4pQVGMqEa8VSNijoWjboRY',
    appId: '1:521798357263:web:ac056d7bd3fc2ee402ee7a',
    messagingSenderId: '521798357263',
    projectId: 'my-project-faeee',
    authDomain: 'my-project-faeee.firebaseapp.com',
    storageBucket: 'my-project-faeee.appspot.com',
    measurementId: 'G-SETBF599RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi2MycMatevAZq9cN1ljLfRSCuyAvner4',
    appId: '1:521798357263:android:8363c4f1a660fc8702ee7a',
    messagingSenderId: '521798357263',
    projectId: 'my-project-faeee',
    storageBucket: 'my-project-faeee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ1AqBWwH9yF1VmQoty99cugfAwdlm05E',
    appId: '1:521798357263:ios:c5094968e4aa19af02ee7a',
    messagingSenderId: '521798357263',
    projectId: 'my-project-faeee',
    storageBucket: 'my-project-faeee.appspot.com',
    iosBundleId: 'com.example.newone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ1AqBWwH9yF1VmQoty99cugfAwdlm05E',
    appId: '1:521798357263:ios:9849d023d4b000df02ee7a',
    messagingSenderId: '521798357263',
    projectId: 'my-project-faeee',
    storageBucket: 'my-project-faeee.appspot.com',
    iosBundleId: 'com.example.newone.RunnerTests',
  );
}
